#include<Comms.hpp>
#include<Accelerator.hpp>

/**
 * Initializes the application with command line arguments.
 *
 * @param argc Number of command line arguments
 * @param argv Array of command line argument strings
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void initialize(int argc, char** argv){
  initializeComms(argc,argv);
  communicators().reportSetup();
  acceleratorInit();
  acceleratorReport();
}
